//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelSpot1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liked_photos
    {
        public int l_id { get; set; }
        public int u_id { get; set; }
        public int p_id { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual User User { get; set; }
    }
}
