//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelSpot1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.Downlaods = new HashSet<Downlaod>();
            this.Liked_photos = new HashSet<Liked_photos>();
            this.Spam_photos = new HashSet<Spam_photos>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public bool p_state { get; set; }
        public bool p_degree { get; set; }
        public int u_id { get; set; }
        public Nullable<int> uc_id { get; set; }
        public Nullable<int> pc_id { get; set; }
        public System.DateTime p_datetime { get; set; }
        public Nullable<bool> p_profilePhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Downlaod> Downlaods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liked_photos> Liked_photos { get; set; }
        public virtual Photo_category Photo_category { get; set; }
        public virtual User_collection User_collection { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spam_photos> Spam_photos { get; set; }
    }
}
