//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelSpot1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spam_photos
    {
        public int sp_id { get; set; }
        public string sp_details { get; set; }
        public int p_id { get; set; }
    
        public virtual Photo Photo { get; set; }
    }
}
