//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelSpot1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Downlaods = new HashSet<Downlaod>();
            this.Liked_photos = new HashSet<Liked_photos>();
            this.Photos = new HashSet<Photo>();
            this.User_collection = new HashSet<User_collection>();
        }
    
        public int u_id { get; set; }
        public string u_first_name { get; set; }
        public string u_last_name { get; set; }
        public string u_email { get; set; }
        public string u_password { get; set; }
        public string u_address { get; set; }
        public string u_mobile { get; set; }
        public string u_about { get; set; }
        public string u_role { get; set; }
        public Nullable<bool> u_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Downlaod> Downlaods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liked_photos> Liked_photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_collection> User_collection { get; set; }
    }
}
